# Generated by Django 5.0.1 on 2024-01-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0002_job_experience_job_requirements_alter_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
    ]
