# Generated by Django 5.0.1 on 2024-01-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0004_company_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_apply_job.job'),
        ),
    ]
