# Generated by Django 5.0.1 on 2024-01-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0005_alter_person_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
