# Generated by Django 5.0.1 on 2024-01-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0006_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
