# Generated by Django 5.0.1 on 2024-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0010_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(default=True, upload_to='files'),
        ),
    ]
