# Generated by Django 5.0.1 on 2024-01-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_job', '0011_person_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.AlterField(
            model_name='person',
            name='apply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easy_apply_job.job'),
        ),
    ]
